JCC = javac

default: GetOnePic.class GetBigPic.class UploadImage.class

GetOnePic.class: GetOnePic.java
	$(JCC) GetOnePic.java
GetBigPic.class: GetBigPic.java
	$(JCC) GetBigPic.java
UploadImage.class: UploadImage.java
	$(JCC) UploadImage.java


clean: 
	rm -f *.class

